GDCM-831 Usar DForm viewer en Mobil
fullstacklabs/gdc-dform-viewer pull request #10
Opened 2021-05-18 13:35 UTC by jferreira-fsl

## Issue Link
https://fullstacklabs.atlassian.net/browse/GDCM-831

## Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed locally.

## ⚠️ Depends on the following PRs:
- https://github.com/fullstacklabs/gdc-movilidad-mobile/pull/105
- https://github.com/fullstacklabs/gdc-movilidad-client/pull/184

2021-05-18 13:47 UTC, jferreira-fsl commented on src/fields/DynamicListFieldBody.js
> -  const renderFields = useCallback(
I had to remove this wrap in `useCallback` because it was causing visually bugs when adding a new item to a dynamic list.

2021-07-09 03:58 UTC, vichugofsl requested changes

2021-07-09 03:58 UTC, vichugofsl commented on src/fields/DateField.test.js
> +            onChange={(e) => {
If is possible let use onChangeHandler.

2021-07-09 03:58 UTC, vichugofsl commented on src/fields/DateField.test.js
>  //   };
Lets remove commented lines.

2021-07-09 03:58 UTC, vichugofsl commented on src/fields/DynamicFieldLineItem.js
>    // allFormFields: PropTypes.array.isRequired,
Lets remove these commented lines.

2021-07-09 03:58 UTC, vichugofsl commented on src/fields/GPSField.test.js
> +
Lets remove these commented lines.

2021-07-09 03:58 UTC, vichugofsl commented on src/schema/fieldDateSchema.js
> +function applyMinAndMaxValues(schema, field) {
Maybe, can use arrow function expression?

2021-07-09 03:58 UTC, vichugofsl commented on src/schema/fieldDateSchema.js
> +function applyMinCurrentDate(schema, field) {
Maybe, can use arrow function expression?

2021-07-09 14:20 UTC, jferreira-fsl commented on src/fields/DateField.test.js
> +            onChange={(e) => {
This is a test file, it's not relevant.

2021-07-09 14:21 UTC, jferreira-fsl commented on src/fields/DateField.test.js
>  //   };
Done.

2021-07-09 14:21 UTC, jferreira-fsl commented on src/fields/DynamicFieldLineItem.js
>    // allFormFields: PropTypes.array.isRequired,
Done.

2021-07-09 14:22 UTC, jferreira-fsl commented on src/fields/GPSField.test.js
> +
Done.

2021-07-09 14:23 UTC, jferreira-fsl commented on src/schema/fieldDateSchema.js
> +function applyMinAndMaxValues(schema, field) {
Done.

2021-07-09 14:23 UTC, jferreira-fsl commented on src/schema/fieldDateSchema.js
> +function applyMinCurrentDate(schema, field) {
Done.

2021-07-09 14:44 UTC, vichugofsl approved these changes

2021-07-09 14:44 UTC, merged